CREATE TABLE hubs.asset
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    customer_id BIGINT                                  NOT NULL,
    asset_name  VARCHAR(255)                            NOT NULL,
    size        VARCHAR(255)                            NOT NULL,
    usable_size VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_asset PRIMARY KEY (id)
);

CREATE TABLE hubs.customer
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     VARCHAR(255)                            NOT NULL,
    surname  VARCHAR(255)                            NOT NULL,
    email    VARCHAR(255)                            NOT NULL,
    password VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_customer PRIMARY KEY (id)
);

CREATE TABLE hubs.customer_authority
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    customer_id BIGINT,
    authority   VARCHAR(255),
    endpoint    VARCHAR(255),
    CONSTRAINT pk_customer_authority PRIMARY KEY (id)
);

CREATE TABLE hubs.money_transactions
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    customer_id      BIGINT,
    amount           DECIMAL,
    transaction_type VARCHAR(255),
    CONSTRAINT pk_money_transactions PRIMARY KEY (id)
);

CREATE TABLE hubs."order"
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    customer_id BIGINT                                  NOT NULL,
    asset_name  VARCHAR(255)                            NOT NULL,
    order_side  VARCHAR(255)                            NOT NULL,
    size        VARCHAR(255)                            NOT NULL,
    price       VARCHAR(255)                            NOT NULL,
    status      VARCHAR(255)                            NOT NULL,
    create_date TIMESTAMP                               NOT NULL,
    CONSTRAINT pk_order PRIMARY KEY (id)
);